version: "3.8"
services:
  whisper_diarizer:
    build: .
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file:
      - .env
    environment:
      - AUDIO_FILE=${AUDIO_FILE}
      - OUTPUT_FILE=${OUTPUT_FILE}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - FASTER_WHISPER=${FASTER_WHISPER}
    volumes:
      - ./audio:/app/audio
      - ./output:/app/output
